'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Emmaliya.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /************************************************
        '''    alert
        '''    Generates a popup and display the passed message
        '''************************************************/
        '''emmaliya.fn.alert = function (message, options) {
        '''    var popup = $(&apos;&lt;div&gt;&lt;div class=&quot;emma-popup&quot; title=&quot;&apos; + emmaliya.currentApplication.Name + &apos;&quot; data-emma-buttons=&quot;[{Text:\&apos;OK\&apos;, Action:\&apos;Cancel\&apos;}]&quot;&gt;&lt;div&gt;&lt;p class=&quot;emma-popup-message&quot;&gt;&lt;/p&gt;&lt;p class=&quot;emma-popup-stack-trace&quot;&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&apos;);
        '''
        '''    $(&apos;body&apos;).append(popup);
        '''
        '''    //mo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap4_emmaliya() As String
            Get
                Return ResourceManager.GetString("bootstrap4_emmaliya", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to body {
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property bootstrap4_emmaliya_css() As String
            Get
                Return ResourceManager.GetString("bootstrap4_emmaliya_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var emmaliya = emmaliya || {};
        '''
        '''(function ($) {
        '''    $.namespace = function (namespaceName, closures) {
        '''
        '''        if ($.fn[namespaceName] === undefined) {
        '''            $.fn[namespaceName] = function executor(context) {
        '''                if (this instanceof executor) {
        '''                    this.__context__ = context;
        '''                }
        '''                else {
        '''                    return new executor(this);
        '''                }
        '''            };
        '''        }
        '''
        '''        $.each(closures, function (closureName, clos [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property emmaliya() As String
            Get
                Return ResourceManager.GetString("emmaliya", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
